# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# Uncomment this line if you're using Swift
use_frameworks!

def import_pods
  pod 'DPValidator', :path => '../'
end

target 'DPValidatorDemo' do
  import_pods
end

target 'DPValidatorDemoTests' do

end

target 'DPValidatorDemoUITests' do

end

